name=LSM6DS3
version=1.0
author=Carlo C. Bragagnolo <carloccbragagnolo@gmail.com>
maintainer=Carlo C. Bragagnolo <carloccbragagnolo@gmail.com>
sentence=Library for SPI communication with the LSM6DS3 sensor.
paragraph= A Library allowing simple interface with the LSM6DS3 sensor, with simple functions to read out the accelerometer, gyroscope and temperatue sensor via SPI. This library has only been tested on the ESP32S3 platform.
url=https://github.com/CarloCBragagnolo/LSM6DS3
architectures=*

